# Generated by Django 5.0 on 2023-12-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='song')),
                ('year', models.IntegerField()),
                ('music', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('Language', models.CharField(max_length=200)),
                ('audio', models.FileField(blank=' ', upload_to='audio')),
            ],
        ),
    ]
